/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/projects": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          description?: parameters["rowFilter.projects.description"];
          created_at?: parameters["rowFilter.projects.created_at"];
          database?: parameters["rowFilter.projects.database"];
          owner_id?: parameters["rowFilter.projects.owner_id"];
          srid?: parameters["rowFilter.projects.srid"];
          slug?: parameters["rowFilter.projects.slug"];
          title?: parameters["rowFilter.projects.title"];
          uuid?: parameters["rowFilter.projects.uuid"];
          data_schema?: parameters["rowFilter.projects.data_schema"];
          topo_schema?: parameters["rowFilter.projects.topo_schema"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["projects"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          description?: parameters["rowFilter.projects.description"];
          created_at?: parameters["rowFilter.projects.created_at"];
          database?: parameters["rowFilter.projects.database"];
          owner_id?: parameters["rowFilter.projects.owner_id"];
          srid?: parameters["rowFilter.projects.srid"];
          slug?: parameters["rowFilter.projects.slug"];
          title?: parameters["rowFilter.projects.title"];
          uuid?: parameters["rowFilter.projects.uuid"];
          data_schema?: parameters["rowFilter.projects.data_schema"];
          topo_schema?: parameters["rowFilter.projects.topo_schema"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          description?: parameters["rowFilter.projects.description"];
          created_at?: parameters["rowFilter.projects.created_at"];
          database?: parameters["rowFilter.projects.database"];
          owner_id?: parameters["rowFilter.projects.owner_id"];
          srid?: parameters["rowFilter.projects.srid"];
          slug?: parameters["rowFilter.projects.slug"];
          title?: parameters["rowFilter.projects.title"];
          uuid?: parameters["rowFilter.projects.uuid"];
          data_schema?: parameters["rowFilter.projects.data_schema"];
          topo_schema?: parameters["rowFilter.projects.topo_schema"];
        };
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          username?: parameters["rowFilter.users.username"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          username?: parameters["rowFilter.users.username"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          username?: parameters["rowFilter.users.username"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  projects: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id?: number;
    /** Format: text */
    description?: string;
    /** Format: timestamp without time zone */
    created_at?: string;
    /** Format: text */
    database?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    owner_id?: number;
    /** Format: integer */
    srid?: number;
    /** Format: text */
    slug?: string;
    /** Format: text */
    title?: string;
    /** Format: uuid */
    uuid?: string;
    /** Format: text */
    data_schema?: string;
    /** Format: text */
    topo_schema?: string;
  };
  users: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id?: number;
    /** Format: timestamp without time zone */
    created_at?: string;
    /** Format: text */
    username?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description projects */
  "body.projects": definitions["projects"];
  "rowFilter.projects.id": string;
  "rowFilter.projects.description": string;
  "rowFilter.projects.created_at": string;
  "rowFilter.projects.database": string;
  "rowFilter.projects.owner_id": string;
  "rowFilter.projects.srid": string;
  "rowFilter.projects.slug": string;
  "rowFilter.projects.title": string;
  "rowFilter.projects.uuid": string;
  "rowFilter.projects.data_schema": string;
  "rowFilter.projects.topo_schema": string;
  /** @description users */
  "body.users": definitions["users"];
  "rowFilter.users.id": string;
  "rowFilter.users.created_at": string;
  "rowFilter.users.username": string;
}

export interface operations {}

export interface external {}
