#!/usr/bin/env bash

db_name=$1


# Export environment variables
export $(grep -v '^#' .env | xargs)


## restore from stdin
echo "Restoring database $db_name from stdin"

# Drop database if it exists
docker compose exec database dropdb -U "$POSTGRES_USER" $db_name

docker compose exec database createdb -U "$POSTGRES_USER" $db_name
cat /dev/stdin | pv | docker compose exec -T database pg_restore -U "$POSTGRES_USER" -d "$db_name"
